version: '3.3'
services:
  frontend:
    container_name: frontend
    build: ./frontend
    image: anisa18/game-library
    ports:
    - target: 5000
      published: 5000
  backend:
    container_name: backend
    build: ./backend
    image: anisa18/database
    ports:
    - target: 5001
      published: 5001